# Printing in Capital Letters

print(chr(ord('a')-32))
print(chr(ord('b')-32))
print(chr(ord('c')-32))
print(chr(ord('d')-32))
print(chr(ord('e')-32)) 
print(chr(ord('f')-32)) 
print(chr(ord('g')-32))
print(chr(ord('h')-32))
print(chr(ord('i')-32))
print(chr(ord('j')-32))
print(chr(ord('k')-32))
print(chr(ord('l')-32))
print(chr(ord('m')-32))
print(chr(ord('n')-32))
print(chr(ord('o')-32))
print(chr(ord('p')-32))
print(chr(ord('q')-32))
print(chr(ord('r')-32))
print(chr(ord('s')-32))
print(chr(ord('t')-32))
print(chr(ord('u')-32))
print(chr(ord('v')-32))
print(chr(ord('w')-32))
print(chr(ord('x')-32))
print(chr(ord('y')-32))
print(chr(ord('z')-32))  

# Printing the Small Letters   
             
print(chr(ord('A')+32))
print(chr(ord('B')+32))
print(chr(ord('C')+32))
print(chr(ord('D')+32))
print(chr(ord('E')+32))
print(chr(ord('F')+32))
print(chr(ord('G')+32))
print(chr(ord('H')+32))
print(chr(ord('I')+32))
print(chr(ord('J')+32))
print(chr(ord('K')+32))
print(chr(ord('L')+32))
print(chr(ord('M')+32))
print(chr(ord('N')+32))
print(chr(ord('O')+32))
print(chr(ord('P')+32))  
print(chr(ord('Q')+32))
print(chr(ord('R')+32))
print(chr(ord('S')+32))
print(chr(ord('T')+32))
print(chr(ord('U')+32))
print(chr(ord('V')+32))
print(chr(ord('W')+32))
print(chr(ord('X')+32))
print(chr(ord('Y')+32))
print(chr(ord('Z')+32))  